### ISSUE TITLE
Example to provide path for server

### ISSUE THREAD

**Issue by smatthews1999** [roylee0704/angular-socket-signalr#1]
Can you please provide a more complete sample of how to configure the server location?

I see no way to provide the remote IP and path of my SignalR server.

For example if I want to use plain signalR hub I have the following in my index.html...

`<script src="http://192.168.1.10/MyServer/signalR/hubs"></script>`

... which configures my hub for me.  That server is not the same location of my client.  However with your lib I see no way to configure that location

Thanks.

**Comment by roylee0704** [comment]
I'm sorry for the late reply, would the following script help?

``` javascript
var mySpecialHub = $.hubConnection('/some/path', {useDefaultPath: false});
```

**Comment by roylee0704** [comment]
Since you do not reply, I will assume that the issue has been resolved. 

Will close this.
